name: Server

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
  pull_request:
    branches:
      - master
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the project
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.5+8'
          cache: 'maven'
      - name: Build the project
        run: mvn -B package --file server/pom.xml
